# Generated by Django 4.2.11 on 2024-05-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vendor', '0002_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='vendor_code',
            field=models.CharField(max_length=200),
        ),
    ]
