# Generated by Django 4.2.11 on 2024-05-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_vendor', '0003_alter_vendor_vendor_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
